// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rentify.Backend.Infraestructure.Persistence.Context;

#nullable disable

namespace Rentify.Backend.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(RentifyContext))]
    partial class RentifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rentify.Backend.Core.Domain.Entities.RentCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RentCars", (string)null);
                });

            modelBuilder.Entity("Rentify.Backend.Core.Domain.Entities.RentCar", b =>
                {
                    b.OwnsOne("Rentify.Backend.Core.Domain.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("RentCarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("RentCarId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("RentCars");

                            b1.WithOwner()
                                .HasForeignKey("RentCarId");
                        });

                    b.OwnsOne("Rentify.Backend.Core.Domain.ValueObjects.PhoneNumber", "WhatsApp", b1 =>
                        {
                            b1.Property<Guid>("RentCarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("WhatsApp");

                            b1.HasKey("RentCarId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("RentCars");

                            b1.WithOwner()
                                .HasForeignKey("RentCarId");
                        });

                    b.OwnsOne("Rentify.Backend.Core.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RentCarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Street");

                            b1.HasKey("RentCarId");

                            b1.ToTable("RentCars");

                            b1.WithOwner()
                                .HasForeignKey("RentCarId");
                        });

                    b.OwnsOne("Rentify.Backend.Core.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("RentCarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("RentCarId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("RentCars");

                            b1.WithOwner()
                                .HasForeignKey("RentCarId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("WhatsApp")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
